version: "3.9"
services:
  llama:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    command: [
      "--model_url", "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_0.gguf",
      "--port", "8080",
      "--host", "0.0.0.0",
      "-n", "2048",
      "--n-gpu-layers", "-1"
    ]
    volumes:
      - ./models:/models
    ports:
      - "8088:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  custom_network:
    driver: bridge