FROM python:3.9-slim

WORKDIR /app


RUN pip install gradio==4.44.1 requests==2.32.3

# Install cpu version for lightweight Docker Image
RUN pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install git+https://github.com/bibekyess/FastRAG.git

COPY fastrag/api.py /app/api.py

EXPOSE 7860

CMD ["python", "/app/api.py"]


