FROM python:3.9-slim

WORKDIR /app

# Install packages
RUN apt-get update && \
    apt-get install -y bash \
                       git \
                       curl \
                       ca-certificates && \
    apt-get install -y --no-install-recommends \
                       build-essential \
                       pkg-config \
                       python3-dev \
                       pandoc && \
    rm -rf /var/lib/apt/lists/*
    
RUN pip install gradio==4.44.1 requests==2.32.3

# Install cpu version for lightweight Docker Image
RUN pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install git+https://github.com/bibekyess/FastRAG.git

COPY fastrag/api.py /app/api.py

EXPOSE 7860

CMD ["python", "/app/api.py"]


